services:
  burn-p2p-bootstrap:
    extends:
      file: ./bootstrap-base.compose.yaml
      service: burn-p2p-bootstrap-base
    build:
      args:
        BURN_P2P_BOOTSTRAP_FEATURES: ${BURN_P2P_BOOTSTRAP_FEATURES:-admin-http,metrics,browser-edge,browser-join,rbac,auth-github,social}
    command: ["/config/community-web.json"]
    volumes:
      - ../config/community-web.json:/config/community-web.json:ro
      - burn-p2p-bootstrap-data:/var/lib/burn-p2p

volumes:
  burn-p2p-bootstrap-data: {}
