services:
  burn-p2p-bootstrap:
    extends:
      file: ./bootstrap-base.compose.yaml
      service: burn-p2p-bootstrap-base
    build:
      args:
        BURN_P2P_BOOTSTRAP_FEATURES: ${BURN_P2P_BOOTSTRAP_FEATURES:-admin-http,metrics,auth-static}
    command: ["/config/trusted-minimal.json"]
    volumes:
      - ../config/trusted-minimal.json:/config/trusted-minimal.json:ro
      - burn-p2p-bootstrap-data:/var/lib/burn-p2p

volumes:
  burn-p2p-bootstrap-data: {}
