#[cfg(not(target_arch = "wasm32"))]
pub mod args;
#[cfg(not(target_arch = "wasm32"))]
pub mod core;
#[cfg(not(target_arch = "wasm32"))]
pub mod correctness;
pub mod data;
pub mod model;
#[cfg(not(target_arch = "wasm32"))]
pub mod scenario;
#[cfg(target_arch = "wasm32")]
pub mod wasm_probe;
